version: '3.4'

services:
  swarm:
    image: 355982936287.dkr.ecr.us-east-2.amazonaws.com/docker_metrics_producer
    hostname: "{{.Node.Hostname}}"
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==worker
    command: ["go", "run", "main.go"]


